apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/round-fusion-426008-d8/back_img
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: host
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: dbname
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
