apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awesome-cats-cert
  namespace: default
spec:
  secretName: awesome-cats-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: thebem.online  # Replace with your domain name
  dnsNames:
  - thebem.online  # Replace with your domain name