apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  host: MzQuNDUuMTkuMTAz
  username: cG9zdGdyZXM=
  password: LmtuOlxFJDxseXI6Z00rRg==
  dbname: cG9zdGdyZXM=
